"""Generate web/types-data.js from app/types.json (the one source of truth for item types).

Run after editing app/types.json:  python scripts/gen_types.py
tests/test_item_types.py fails when the checked-in file is stale."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def render() -> str:
    data = json.loads((ROOT / "app" / "types.json").read_text())
    body = json.dumps(data, indent=2).replace("\n", "\n  ")
    return f"""// GENERATED by scripts/gen_types.py from app/types.json. Do not edit.
(function (root, factory) {{
  if (typeof module === "object" && module.exports) {{
    module.exports = factory();
  }} else {{
    root.TypesData = factory();
  }}
}})(typeof self !== "undefined" ? self : this, function () {{
  "use strict";
  return {body};
}});
"""


if __name__ == "__main__":
    (ROOT / "web" / "types-data.js").write_text(render())
