// GENERATED by scripts/gen_types.py from app/types.json. Do not edit.
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.TypesData = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  return {
    "todo": {
      "label": "Todo",
      "icon": "check",
      "fields": [
        "title",
        "due_date",
        "repeat",
        "color",
        "links",
        "blocked_by",
        "references",
        "attachments",
        "priority"
      ],
      "hasCheckbox": true,
      "appearsInNextUp": true,
      "triggersAutodone": true,
      "countsInBadge": true,
      "showsProgress": true,
      "notifies": true,
      "allowsUserChildren": true,
      "editable": true,
      "description": "Something to do, with a checkbox and an optional due date.",
      "defaultChildType": "todo"
    },
    "list": {
      "label": "List",
      "icon": "list",
      "fields": [
        "title",
        "color",
        "links",
        "references",
        "attachments"
      ],
      "hasCheckbox": false,
      "appearsInNextUp": false,
      "triggersAutodone": false,
      "countsInBadge": false,
      "showsProgress": false,
      "notifies": false,
      "allowsUserChildren": true,
      "editable": true,
      "description": "A plain group of items, with no checkbox or due date.",
      "defaultChildType": "todo"
    },
    "project": {
      "label": "Project",
      "icon": "folder",
      "fields": [
        "title",
        "color",
        "links",
        "references",
        "attachments"
      ],
      "hasCheckbox": false,
      "appearsInNextUp": false,
      "triggersAutodone": false,
      "countsInBadge": false,
      "showsProgress": true,
      "notifies": false,
      "allowsUserChildren": true,
      "editable": true,
      "description": "A group that shows how many of its todos are done.",
      "defaultChildType": "todo"
    },
    "calendar": {
      "label": "Calendar",
      "icon": "calendar",
      "fields": [
        "title",
        "calendar_url",
        "color"
      ],
      "hasCheckbox": false,
      "appearsInNextUp": false,
      "triggersAutodone": false,
      "countsInBadge": false,
      "showsProgress": false,
      "notifies": false,
      "allowsUserChildren": false,
      "editable": true,
      "description": "A live calendar feed; its events sync in automatically.",
      "defaultChildType": "calendar_event"
    },
    "calendar_event": {
      "label": "Event",
      "icon": "calendar",
      "fields": [
        "title",
        "due_date",
        "priority",
        "location",
        "end_date",
        "repeat_summary",
        "conference_url",
        "attendees",
        "notes"
      ],
      "hasCheckbox": false,
      "appearsInNextUp": true,
      "triggersAutodone": false,
      "countsInBadge": false,
      "showsProgress": false,
      "notifies": true,
      "allowsUserChildren": false,
      "editable": false,
      "description": "One event from a synced calendar. Read-only.",
      "defaultChildType": "calendar_event"
    }
  };
});
