// GENERATED by scripts/gen_types.py from app/types.json. Do not edit.
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.TypesData = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  return {
    "todo": {
      "label": "Todo",
      "icon": "check",
      "fields": [
        "title",
        "due_date",
        "repeat",
        "color",
        "links",
        "blocked_by",
        "references"
      ],
      "hasCheckbox": true,
      "appearsInNextUp": true,
      "triggersAutodone": true,
      "countsInBadge": true,
      "showsProgress": true,
      "notifies": true
    },
    "list": {
      "label": "List",
      "icon": "grip",
      "fields": [
        "title",
        "color",
        "links",
        "references"
      ],
      "hasCheckbox": false,
      "appearsInNextUp": false,
      "triggersAutodone": false,
      "countsInBadge": false,
      "showsProgress": false,
      "notifies": false
    },
    "project": {
      "label": "Project",
      "icon": "copy",
      "fields": [
        "title",
        "color",
        "links",
        "references"
      ],
      "hasCheckbox": false,
      "appearsInNextUp": false,
      "triggersAutodone": false,
      "countsInBadge": false,
      "showsProgress": true,
      "notifies": false
    }
  };
});
